apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: levikobi/face-recognition-service
      context: face-recognition-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'internals/**/*.go'
            dest: .
