generate:
#	protoc --go_out=. --go_opt=paths=source_relative \
#        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
#        protos/face-recognition-service.proto


	protoc --go_out=golang/face-recognition --go_opt=paths=source_relative \
        --go-grpc_out=golang/face-recognition --go-grpc_opt=paths=source_relative \
        protos/face-recognition-service.proto
