// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package face_recognition_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FaceRecognitionClient is the client API for FaceRecognition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceRecognitionClient interface {
	AddPerson(ctx context.Context, in *AddPersonRequest, opts ...grpc.CallOption) (*AddPersonResponse, error)
	FindPerson(ctx context.Context, in *FindPersonRequest, opts ...grpc.CallOption) (*FindPersonResponse, error)
}

type faceRecognitionClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionClient(cc grpc.ClientConnInterface) FaceRecognitionClient {
	return &faceRecognitionClient{cc}
}

func (c *faceRecognitionClient) AddPerson(ctx context.Context, in *AddPersonRequest, opts ...grpc.CallOption) (*AddPersonResponse, error) {
	out := new(AddPersonResponse)
	err := c.cc.Invoke(ctx, "/protos.FaceRecognition/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionClient) FindPerson(ctx context.Context, in *FindPersonRequest, opts ...grpc.CallOption) (*FindPersonResponse, error) {
	out := new(FindPersonResponse)
	err := c.cc.Invoke(ctx, "/protos.FaceRecognition/FindPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecognitionServer is the server API for FaceRecognition service.
// All implementations must embed UnimplementedFaceRecognitionServer
// for forward compatibility
type FaceRecognitionServer interface {
	AddPerson(context.Context, *AddPersonRequest) (*AddPersonResponse, error)
	FindPerson(context.Context, *FindPersonRequest) (*FindPersonResponse, error)
	mustEmbedUnimplementedFaceRecognitionServer()
}

// UnimplementedFaceRecognitionServer must be embedded to have forward compatible implementations.
type UnimplementedFaceRecognitionServer struct {
}

func (UnimplementedFaceRecognitionServer) AddPerson(context.Context, *AddPersonRequest) (*AddPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPerson not implemented")
}
func (UnimplementedFaceRecognitionServer) FindPerson(context.Context, *FindPersonRequest) (*FindPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPerson not implemented")
}
func (UnimplementedFaceRecognitionServer) mustEmbedUnimplementedFaceRecognitionServer() {}

// UnsafeFaceRecognitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServer will
// result in compilation errors.
type UnsafeFaceRecognitionServer interface {
	mustEmbedUnimplementedFaceRecognitionServer()
}

func RegisterFaceRecognitionServer(s grpc.ServiceRegistrar, srv FaceRecognitionServer) {
	s.RegisterService(&FaceRecognition_ServiceDesc, srv)
}

func _FaceRecognition_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.FaceRecognition/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServer).AddPerson(ctx, req.(*AddPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognition_FindPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServer).FindPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.FaceRecognition/FindPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServer).FindPerson(ctx, req.(*FindPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceRecognition_ServiceDesc is the grpc.ServiceDesc for FaceRecognition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.FaceRecognition",
	HandlerType: (*FaceRecognitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _FaceRecognition_AddPerson_Handler,
		},
		{
			MethodName: "FindPerson",
			Handler:    _FaceRecognition_FindPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/face-recognition-service.proto",
}
